#!/usr/bin/env python3
"""
Send CPR report via email
"""
import sys
import argparse
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
from db_utils import get_team_rankings, get_db

def generate_html_report(season_year=2025):
 """Generate HTML email report"""
 rankings = get_team_rankings(season_year)
 
 # Get league metrics
 with get_db() as conn:
 cursor = conn.cursor()
 league_metrics = cursor.execute("""
 SELECT gini_coefficient, league_health_index
 FROM league_metrics
 WHERE season_id = (SELECT season_id FROM seasons WHERE season_year = ?)
 ORDER BY calculation_date DESC
 LIMIT 1
 """, (season_year,)).fetchone()
 
 gini = league_metrics[0] if league_metrics else 0
 lhi = league_metrics[1] if league_metrics else 0
 
 html = f"""
 <html>
 <head>
 <style>
 body {{ font-family: Arial, sans-serif; margin: 20px; }}
 h1 {{ color: #1a73e8; }}
 table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
 th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
 th {{ background-color: #1a73e8; color: white; }}
 tr:nth-child(even) {{ background-color: #f2f2f2; }}
 .metric {{ font-size: 18px; margin: 10px 0; }}
 .footer {{ margin-top: 40px; font-size: 12px; color: #666; }}
 </style>
 </head>
 <body>
 <h1> CPR v2.0 Weekly Report</h1>
 <p><strong>Date:</strong> {datetime.now().strftime('%B %d, %Y')}</p>
 
 <h2> League Metrics</h2>
 <div class="metric">Gini Coefficient: <strong>{gini:.3f}</strong></div>
 <div class="metric">League Health Index: <strong>{lhi:.3f}</strong></div>
 
 <h2> Power Rankings</h2>
 <table>
 <tr>
 <th>Rank</th>
 <th>Team</th>
 <th>CPR</th>
 <th>SLI</th>
 <th>BSI</th>
 <th>Ingram</th>
 <th>Alvarado</th>
 <th>Zion</th>
 </tr>
 """
 
 for team in rankings:
 html += f"""
 <tr>
 <td>{team['rank']}</td>
 <td><strong>{team['team_name']}</strong></td>
 <td>{team['cpr_score']:.3f}</td>
 <td>{team['sli_z']:.2f}</td>
 <td>{team['bsi_z']:.2f}</td>
 <td>{team['ingram_z']:.2f}</td>
 <td>{team['alvarado_z']:.2f}</td>
 <td>{team['zion_z']:.2f}</td>
 </tr>
 """
 
 html += """
 </table>
 
 <h2> What the Numbers Mean</h2>
 <ul>
 <li><strong>CPR:</strong> Overall power score (higher is better)</li>
 <li><strong>SLI:</strong> Starting lineup strength</li>
 <li><strong>BSI:</strong> Bench depth</li>
 <li><strong>Ingram:</strong> Positional balance (HHI-based)</li>
 <li><strong>Alvarado:</strong> Value per dollar</li>
 <li><strong>Zion:</strong> Health + injury prediction</li>
 </ul>
 
 <div class="footer">
 <p>Generated by CPR v2.0 — Commissioner's Power Rankings</p>
 <p>Built with game theory, economics, and information theory</p>
 </div>
 </body>
 </html>
 """
 
 return html

def send_email(recipient, subject, html_content, sender_email=None, sender_password=None):
 """Send email via SMTP"""
 # For production, use SendGrid or similar service
 # This is a placeholder implementation
 
 msg = MIMEMultipart('alternative')
 msg['Subject'] = subject
 msg['From'] = sender_email or "cpr-reports@yourdomain.com"
 msg['To'] = recipient
 
 html_part = MIMEText(html_content, 'html')
 msg.attach(html_part)
 
 # TODO: Implement actual email sending
 # For now, save to file
 output_path = Path(__file__).parent.parent / "reports" / f"cpr_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
 output_path.parent.mkdir(exist_ok=True)
 
 with open(output_path, 'w') as f:
 f.write(html_content)
 
 print(f" Report saved to: {output_path}")
 print(f" Email would be sent to: {recipient}")
 
 return True

def main():
 parser = argparse.ArgumentParser(description="Send CPR report via email")
 parser.add_argument("--email", default="ezialb777@gmail.com", help="Recipient email")
 parser.add_argument("--season", type=int, default=2025, help="Season year")
 args = parser.parse_args()
 
 print("=" * 70)
 print("CPR v2.0 - Email Report Generator")
 print("=" * 70)
 
 # Generate report
 print("\n Generating report...")
 html = generate_html_report(args.season)
 
 # Send email
 print(f"\n Sending to {args.email}...")
 subject = f"CPR v2.0 Weekly Report - {datetime.now().strftime('%B %d, %Y')}"
 send_email(args.email, subject, html)
 
 print("\n Done!")

if __name__ == "__main__":
 main()
